[package]
name = "contrafact"
version = "0.1.0"
authors = ["Michael Dougherty <maackle.d@gmail.com>"]
edition = "2018"

[dependencies]
arbitrary = {version = "1.0", features = ["derive"]}
derive_more = "0.99"
itertools = "0.10"
predicates = { git = "https://github.com/maackle/contrafact-predicates-rs.git", branch = "main" }

[dev-dependencies]
once_cell = "1.5"
rand = "0.7"

# predicates = { path = "../contrafact-predicates" }
